### ISSUE TITLE
OpenNeuro error for ID 1000

### ISSUE THREAD

**Issue by FeHoff** [NILAB-UvA/AOMIC.github.io#2]
[ID1000: https://openneuro.org/datasets/ds002895](https://openneuro.org/datasets/ds003097) shows the following for me:
> Error: GraphQL error: You do not have access to read this dataset.
> Please support us by documenting the issue with FreshDesk.

**Comment by lukassnoek** [comment]
Oops sorry, completely missed this. The dataset ID for ID1000 changed. I fixed it on the website now!
